export enum PostMessageAction {
    AddRule,
    UpdateRule,
    UpdateRuleNew,
    DeleteRule,
    DeleteRuleById,
    GetStorageRules,
    GetRuleById,
    EnableRule,
    DissableRule,
    Log,
    ERASE,
    GetUserId,
    ChangeRuleStatusById,
}