export const PostMessageAction = {
  AddRule: 0,
  UpdateRule: 1,
  UpdateRuleNew: 2,
  DeleteRules: 3,
  DeleteRule: 4,
  GetStorageRules: 5,
  GetRule: 6,
  EnableRule: 7,
  DissableRule: 8,
  Log: 9,
  GetUserId: 10,
  ChangeRuleStatusById: 12,
  CopyRuleById: 13,
  UpdateTimestamp: 14,
  ExportRules: 15,
  ImportRules: 16,
};
