export enum PostMessageAction {
    AddRule,
    UpdateRule,
    UpdateRuleNew,
    DeleteRule,
    DeleteRuleById,
    GetRules,
    GetStorageRules,
    GetRuleById,
    EnableRule,
    DissableRule,
    Log,
    Reset,
    GetUserId,
}